name: Lint Code Base
on: [push, pull_request]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_GOOGLE_JAVA_FORMAT: false
          VALIDATE_GOOGLE_JAVA_FORMAT: true
          VALIDATE_JAVA: true
          SAVE_SUPER_LINTER_OUTPUT: true
          OUTPUT_FORMAT: html
        continue-on-error: true

      - name: List contents of linter output directory (for debugging)
        run: ls -R ${DEFAULT_WORKSPACE}/${SUPER_LINTER_OUTPUT_DIRECTORY_NAME}/super-linter

      - name: Upload Linter Report As Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linter-report
          path: ${DEFAULT_WORKSPACE}/${SUPER_LINTER_OUTPUT_DIRECTORY_NAME}/super-linter/*.html
