name: Lint Code Base
on: [push, pull_request]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    env:
      RUN-LOCAL: false
      CHECKSTYLE_FILE_PATH: config/checkstyle/checkstyle.xml  # Set it at the job level
      VALIDATE_ALL_CODEBASE: true
      VALIDATE_JAVA: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          LINTER_RULES_PATH: ${{ env.LINTER_RULES_PATH }}  # Reference the job-level variable
          VALIDATE_ALL_CODEBASE: ${{ env.VALIDATE_ALL_CODEBASE }}
          VALIDATE_JAVA: ${{ env.VALIDATE_JAVA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Show environment variables for debugging
        run: |
            echo "LINTER_RULES_PATH=${{ env.LINTER_RULES_PATH }}"


