name: Lint Code Base
on: [push, pull_request]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_GOOGLE_JAVA_FORMAT: true
          VALIDATE_GOOGLE_JAVA_FORMAT: true
          VALIDATE_JAVA: true
          
      - name: Commit and push fixes
        run: |
          git config --global user.name "flyingapricot"
          git config --global user.email "neerajkumbar44@gmail.com"
          git add .
          git commit -m "Apply Google Java Format fixes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

